name: "Build and Scan JuiceShop"

on: [push]

jobs:
  build-juice-shop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - run: npm install
      - run: npm link @angular/cli
      - run: npm run build --if-present
      - run: npm test
  njsscan:
    runs-on: ubuntu-latest
    name: njsscan check
    steps:
      - uses: actions/checkout@v1
      - name: njsscan
        id: njsscan
        uses: ajinabraham/njsscan-action@v5
        with:
          args: '. --output sast-result'
      - name: Upload Report artifact when job fails
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: sast-report-failure
          path: ./sast-result
      - name: Upload Report artifact
        uses: actions/upload-artifact@v1
        with:
          name: sast-report
          path: ./sast-result
